### ISSUE TITLE
Autodoc is not able to pick up the shared.data items and put it on a report

### ISSUE THREAD

**Issue by sqlkamal** [Traap/autodoc#84]
Autodoc is not able to pick up the shared.data items and put it on a report

Copy and Paste(Replace if exists) the data folder from git-client folder to one of the drivers folder. Generate the report. Look at the very first page. Logo and Page X of Y is missing.

I could not attache the report as Zen Hub was throwing an error.

**Comment by Traap** [comment]
[tool-validation 56](https://github.com/Traap/tool-validation/issues/56) demonstrates how this is accomplished.
