### ISSUE TITLE
Find a way to do substitution in tex file from amber cmd line

### ISSUE THREAD

**Issue by qaautotrain** [Traap/autodoc#88]
Sample : 

\documentclass[10pt]{tlc-article}
\begin{document}
  \global\def\configurationitem{${BROWSER}$ driver-ruby}
  \tlcTitlePageAndTableOfContents
    {${BROWSER}$ Driver Validation Package}
    {Data Management Software Solutions}
    {Throughout this document watir, an open source family of Ruby libraries is the Configuration
     Item that is being validated and Report Package is Driver Report Package.
    ${BROWSER}$ Driver is considered validated after this Report Package has been executed,
     test evidence has been obtained and that test evidence supports the conclusion
     the Intended Use Requirements (IUR) have been satisfied.}
  \input{\toolTestDir/main.tex}
\end{document}

Need : If the amber cmd line for tool-validation can pass the -b/--BROWSER value in tex files. In above sample case, think about printing Chrome/IE/Firefox instead of  {${BROWSER}$.

**Comment by Traap** [comment]
This work will no be done.  Amber will not modify LaTeX source files.
